apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kesh.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kesh.labels" . | nindent 4 }}
  ports:
    - name: resp
      port: {{ .Values.ports.resp }}
      targetPort: resp
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    {{- include "kesh.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kesh.labels" . | nindent 4 }}
  ports:
    - name: resp
      port: {{ .Values.ports.resp }}
      targetPort: resp
