// The binary. linuxX64 only: it is the target that ships (research D-2), its transport is kesh's own
// `epoll` loop (research D-31), and nothing here is meant to run on the JVM.
plugins {
    alias(wip.plugins.kotlinMultiplatform)
    alias(libs.plugins.sborkaKmp)
    alias(libs.plugins.sborkaLint)
    alias(libs.plugins.sborkaNativeService)
}

// The allocator page size in KiB (research D-19): 256 unless `-Pkesh.allocatorPageSize=16` builds the
// other arm for a comparison (B-30). One value, read once: it sets the compiler option below and the
// constant the binary reports it by, so a measured process can say which arm it is.
val allocatorPageSizeKb: Int =
    providers.gradleProperty("kesh.allocatorPageSize").orNull?.let { raw ->
        requireNotNull(raw.toIntOrNull()?.takeIf { it > 0 }) { "kesh.allocatorPageSize is a size in KiB: $raw" }
    } ?: 256

// Before the target is declared: the convention reads these when `linuxX64()` creates the executable.
nativeService {
    entryPoint = "io.github.youndie.kesh.server.main"
    baseName = "kesh"

    // 256 KiB allocator pages, the compiler's default — not the 16 sborka sets for every native
    // service. The collector's second stop-the-world pause walks and frees the allocator's pages
    // (PageStore::PrepareForGC), so it follows the page count: on a quarter of the reference dataset,
    // 16 KiB pages paused 8–10 ms at the median and 84–139 ms at p99, 256 KiB pages 0.8 ms and 8–18 ms,
    // with 1 % more resident memory (B-19, research D-19). 16 KiB buys back per-thread pages in
    // services with many threads and small heaps; kesh is the opposite.
    allocatorPageSize = allocatorPageSizeKb
}

// `BuildInfo.kt`: what the binary was built with, for the startup line and `/metrics` (B-30).
val generateBuildInfo =
    tasks.register("generateBuildInfo") {
        val pageSize = allocatorPageSizeKb
        val out = layout.buildDirectory.dir("generated/buildInfo/kotlin")
        inputs.property("allocatorPageSizeKb", pageSize)
        outputs.dir(out)
        doLast {
            val file = out.get().file("io/github/youndie/kesh/server/BuildInfo.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                |package io.github.youndie.kesh.server
                |
                |/** Generated by `server/build.gradle.kts` from `-Pkesh.allocatorPageSize` (B-30). */
                |object BuildInfo {
                |    /** The allocator's page size in KiB: the compiler's `fixedBlockPageSize` (research D-19). */
                |    const val ALLOCATOR_PAGE_SIZE_KB: Int = $pageSize
                |}
                |
                """.trimMargin(),
            )
        }
    }

ktlint {
    filter { exclude { it.file.path.contains("/build/generated/") } }
}

kotlin {
    linuxX64 {
        // The collector's log, for measurements only (B-23): `-Pkesh.runtimeLogs=true`. A compiler flag,
        // not a switch, so a measured binary is a different binary — its md5 goes in the report.
        if (providers.gradleProperty("kesh.runtimeLogs").orNull == "true") {
            binaries.all { freeCompilerArgs += "-Xruntime-logs=gc=info,gcScheduler=info" }
        }
    }

    sourceSets {
        nativeMain {
            kotlin.srcDir(generateBuildInfo)
        }
        nativeMain.dependencies {
            implementation(project(":resp"))
            implementation(project(":store"))
            implementation(project(":snapshot"))
            implementation(libs.kore.core)
            implementation(wip.kotlinx.coroutines.core)
        }
        // The tests talk to the server as a client would, through `ktor-network`'s client sockets; the
        // server itself no longer uses it (research D-31). The version is the shared catalog's `ktor`
        // (3.6.0), read rather than repeated (research D-6).
        nativeTest.dependencies {
            implementation("io.ktor:ktor-network:${wip.versions.ktor.get()}")
        }
    }
}
